from pathlib import Path
import json,subprocess,hashlib,collections,shutil
root=Path.cwd();plan='2026.10.01-№1-AZGUARD-V1';art=root/'plans'/plan/'artifacts/P4.13-execution';api='/home/vostrikov/projects/packages/swissknifeman/packages/task/scripts/plan.py'
a=json.load(open(art/'review-response.json'));b=json.load(open(art/'review-supplement-response.json'));decoder=json.JSONDecoder()
def payload(x):return decoder.raw_decode(x['text'][x['text'].index('{'):])[0]
v=payload(a);s=payload(b);m=json.load(open(art/'review-launch.json'))
assert a['stopReason']==b['stopReason']=='end_turn' and a['sessionId']==b['sessionId']==m['session']
assert json.load(open(art/'review-exit.json'))['exit_code']==json.load(open(art/'review-supplement-exit.json'))['exit_code']==0
v['findings']=s['findings'];v['verdict']=s['verdict'];v['validation_verdict']=s['validation_verdict'];v['input_completeness']=s['input_completeness'];v['reviewed_files']=list(dict.fromkeys(v['reviewed_files']+s['additional_read_files']));v['explain']=s['explain'];v['checks']['V7']='Fresh no-cache native process exit0,205 core files,99.8%; V7-fresh.json/log/type-report; initial cached receipt retained.'
assert v['verdict']=='GREEN' and v['validation_verdict']=='RED'
(art/'review-verdict.json').write_text(json.dumps(v,ensure_ascii=False,indent=2))
before=json.load(open(art/'product-before.json'));after={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in before};assert before==after;(art/'product-after-review.json').write_text(json.dumps(after,indent=2))
q=json.load(open(art/'qualification-summary.json'));q['review']={'verdict':v['verdict'],'validation_verdict':v['validation_verdict'],'findings':v['findings'],'provider':'grok','model':'grok-4.7','effort':'high','session':m['session'],'context_parameter':None,'completed_rounds':2,'second_round':'Narrow mandatory-input completeness supplement in same session; no full audit or product repair','transport_exit_codes':[0,0],'stop_reason':'end_turn','product_unchanged':True};(art/'qualification-summary.json').write_text(json.dumps(q,ensure_ascii=False,indent=2))
sd=next((Path(m['home'])/'sessions').rglob('summary.json'));native=json.load(open(sd));(art/'review-native-route-final.json').write_text(json.dumps({k:native.get(k) for k in ['info','current_model_id','reasoning_effort','sandbox_profile','session_kind']},indent=2));shutil.copy2('/tmp/azguard-p413-supplement.py',art/'review-supplement-runner.py')
# Provider event history is provenance; retain only tool metadata, never auth or full session internals.
calls=[]
for line in (sd.parent/'updates.jsonl').read_text().splitlines():
 try:x=json.loads(line)
 except json.JSONDecodeError:continue
 calls.append(x) if 'tool_call' in json.dumps(x) and 'session/update' not in str(x.get('method','')) else None
(art/'review-attestation.json').write_text(json.dumps({'session':m['session'],'actual_route':{'provider':'grok','model':native.get('current_model_id'),'effort':native.get('reasoning_effort')},'independent_fresh_initial_session':True,'supplement_same_native_session':True,'no_context_parameter':True,'tools_allowlisted':['read_file','grep','list_dir'],'native_extra_tools':['search_tool','use_tool'],'native_mcp_tool_calls_observed':0,'no_tests_or_writes_by_reviewer':True,'code_green_acceptance_red':True,'product_unchanged':True,'auto_compaction_during_supplement':True,'initial_model_usage':a.get('modelUsage'),'supplement_model_usage':b.get('modelUsage')},ensure_ascii=False,indent=2))
sections=[{'id':'verdict','title':'P4.13 — независимое ревью среза; код GREEN, приёмка RED','text':'Native Grok4.7/high, session '+m['session']+'. Code GREEN: нет blocker/major. Acceptance RED: V4 Pint exit1. Read-only review delivered; P4.13 blocked until owning P4.15 lint repair or explicit accepted deviation. No product changes. Fresh native final whole-scope pass plus a bounded same-session input-completeness supplement; both exit0/end_turn, no context parameter.'}, {'id':'findings','title':'Находки и owning items','text':json.dumps(v['findings'],ensure_ascii=False,indent=2)}, {'id':'checklist','title':'Проверка десяти инвариантов','text':json.dumps(v['checklist'],ensure_ascii=False,indent=2)}, {'id':'inputs','title':'Обязательные входы и остатки','text':json.dumps({'input_completeness':v['input_completeness'],'residual_owners':v['residual_owners'],'reviewed_files':v['reviewed_files']},ensure_ascii=False,indent=2)}, {'id':'checks','title':'Проверки и границы','text':'Core2529/372805, Arch72/314; each PostgreSQL16.14/MySQL8.4.10/MariaDB10.11.19 scoped engines14/130; mutationsR11/R13/R14 controlsGREEN/mutantsRED; PHPStan core0errors; API0; fresh core type99.8%,205reported files,exit0; product hashes unchanged. PintRED only missing comma ContextRolesTest.php:28. Owner-scoped V1/V4/V5/V7 exclude unchanged Filament/ecosystem; V2 merged into V1, no duplicate suite; V3 existing healthy SQL containers, no restart/unrelated P3 engine reruns. Optional PHPStan turbo warning disclosed, not a failed analysis. Initial cached type pass and masked child-exit wrapper preserved; explicit fresh receipt captured. Review initial required-input omission corrected by same-session supplement; inaccurate second lint location withdrawn, history preserved. Source artifacts: artifacts/P4.13-execution/qualification-summary.json, review-verdict.json, review-{response,supplement-response,native-route-final,attestation}.json, product-{before,after-review}.json; exact argv/exits/raw logs in V*.json/log.'}]
doc={'$schema':'urn:swissknifeman:task:plan:document:v1','id':'findings-P4-slice-review','title':'P4.13 — срез-review авторизации: код GREEN, приёмка RED','sections':sections,'applies_to':['P4.13','P4.15']};temp=Path('/tmp/azguard-p413-findings.json');temp.write_text(json.dumps(doc,ensure_ascii=False,indent=2))
def run(args):subprocess.run(['python3',api,*args],cwd=root,check=True)
run(['add-document',plan,'--file',str(temp)])
run(['log',plan,'P4.13','--type','note','--summary','Final native Grok4.7/high codeGREEN/validationRED; sole minor P4.15 comma ContextRolesTest.php:28. Session '+m['session']+', no context parameter, exit0/end_turn. Whole scope plus same-session mandatory-input completeness supplement; no product repair or repeated suites. Product hashes unchanged; findings knowledge/findings-P4-slice-review.json and artifacts/P4.13-execution/review-verdict.json.'])
run(['finish',plan,'P4.13','--status','blocked','--check','V1=0','--check','V2=0','--check','V3=0','--check','V4=1','--check','V5=0','--check','V6=0','--check','V7=0','--check','V8=0','--actor','codex/gpt-6.1-sol/high','--notes','Read-only review completed. Independent codeGREEN, no blocker/major; validationRED V4, one minor lint owned by closed P4.15. User-scoped checks and merged/reused execution mapping documented; no unchanged package checks claimed. See knowledge/findings-P4-slice-review.json and artifacts/P4.13-execution/qualification-summary.json.','--escalation','P4.15 owning repair: add trailing comma in tests/Acceptance/Crm/ContextRolesTest.php:28 and run affected Pint; choose owning repeat/repair mechanism or explicitly accept V4 deviation. P4.13 excludes product edits and cannot be accepted GREEN with V4=1.'])
