from pathlib import Path
import os,json,subprocess,time
root=Path('/home/vostrikov/projects/packages/azguard'); art=root/'plans/2026.10.01-№1-AZGUARD-V1/artifacts/P4.13-execution'; meta=json.load(open(art/'review-launch.json'))
prompt='''Complete a narrow input-completeness question in the SAME independent P4.13 review session. Your final report omitted mandatory audits/2026-09-29-audit/opus/17-crm-acceptance-tests.md and 14-verification.md, and the reviewed owning contracts P4.1-P4.7/P4.15-P4.19. Explicitly read those two documents and the included owners' contracts/P4.<id>.json (1,2,3,4,5,6,7,15,16,17,18,19); compare their in-scope acceptance/residual ownership with your already-reviewed current code and evidence. No tests, no new full audit, no subagents, no repair. Read-only tool operations only. Return compact final JSON {verdict,validation_verdict,findings,input_completeness,additional_read_files,explain}; either preserve or amend your previous substantive findings with evidence. P4.8+ future APIs remain outside scope. Existing gateRED must remain disclosed.
Executor scratch Pint copy shows exactly ONE changed trailing comma at ContextRolesTest.php:28; the World::compile argument at123-127 already has a comma, so correct that extraneous part of P413-V4-PINT.scenario. Preserve raw initial finding in history. Fresh explicitly captured no-cache V7 process exit0,205corefiles,99.8%; no product edits. This completes the existing whole-scope review; do not reread sources without a new concrete question.'''
(art/'review-supplement-prompt.txt').write_text(prompt)
args=['/home/vostrikov/.local/bin/grok','--cwd',meta['cwd'],'--model','grok-4.7','--reasoning-effort','high','--resume',meta['session'],'--sandbox','off','--permission-mode','dontAsk','--tools','read_file,grep,list_dir','--deny','Bash','--deny','Edit','--deny','Write','--deny','MCPTool(*)','--no-subagents','--disable-web-search','--output-format','json','--prompt-file',str(art/'review-supplement-prompt.txt')]
(art/'review-supplement-launch.json').write_text(json.dumps({'argv':args,'session':meta['session'],'context_parameter':None,'question':'Mandatory source and owning contract completeness; correct one extraneous lint allegation'},indent=2));t=time.monotonic()
with (art/'review-supplement-response.json').open('w') as out,(art/'review-supplement-stderr.log').open('w') as err:
 code=subprocess.run(args,cwd=meta['cwd'],env=dict(os.environ,GROK_HOME=meta['home']),stdout=out,stderr=err).returncode
(art/'review-supplement-exit.json').write_text(json.dumps({'exit_code':code,'duration_seconds':round(time.monotonic()-t,2),'session':meta['session']},indent=2));print('supplement native exit',code,flush=True)
