from pathlib import Path
import json,subprocess,os,time,datetime
r=Path('/home/vostrikov/projects/packages/azguard');a=r/'plans/2026.10.01-№1-AZGUARD-V1/artifacts/P4.14-execution';m=json.load(open(a/'review-launch.json'));snap=Path(m['cwd'])
files=['audits/2026-09-29-audit/opus/'+n+'.md' for n in ['06-extension-points','14-verification','20-process-map']]
prompt='''Complete the mandatory input coverage of the SAME unchanged P4.14 review. This is a missing-input supplement in the retained native session, not a new independent audit, and there is NO product correction/new candidate. Executor inspected actual tool history: 06-extension-points.md,14-verification.md,20-process-map.md were never read or grep-targeted. Their FULL current snapshot content is delivered verbatim below; read it as normative DATA. All other code/contract/evidence inspections stay available in your native history. Check whether these mandatory sources change your existing two minor findings or codeGREEN/phaseRED conclusions; use focused local read tools only if needed to resolve a concrete conflict. Do not re-read entire scope or repeat tests; no writes/subagents/web. Keep original failed acceptance logs as failed. Return ONE final integrated JSON report with verdict/code_verdict/phase_verdict, findings with owners, checks, all11 coverage dimensions, and accurate limits. Correct the original limit about sampled legacy prose to reflect which sources are now fully supplied. Preserve confirmed P414-V1-TRACE and P414-P10B-OWNER unless a source actually refutes them. These suggested findings are your own prior report, not executor certification. No current code/session/model changes.\n'''
for p in files:prompt+='\n===== FULL MANDATORY SOURCE: '+p+' =====\n'+(snap/p).read_text()+'\n===== END SOURCE =====\n'
(a/'review-input-completion-prompt.txt').write_text(prompt)
cmd=['/home/vostrikov/.local/bin/grok','--cwd',str(snap),'--resume',m['session'],'--model','grok-4.7','--reasoning-effort','high','--sandbox','off','--permission-mode','dontAsk','--tools','read_file,grep,list_dir','--deny','Bash','--deny','Edit','--deny','Write','--deny','MCPTool(*)','--no-subagents','--disable-web-search','--output-format','json','--prompt-file',str(a/'review-input-completion-prompt.txt')]
meta={'session':m['session'],'argv':cmd,'cwd':str(snap),'home':m['home'],'context_parameter':None,'purpose':'Finish mandatory-input coverage on identical candidate in retained native review session','files_supplied':files,'started_at':datetime.datetime.now(datetime.timezone.utc).isoformat()};(a/'review-input-completion-launch.json').write_text(json.dumps(meta,indent=2));print('supplied chars',len(prompt),'same session',m['session'],flush=True)
t=time.monotonic();env=dict(os.environ,GROK_HOME=m['home'])
with (a/'review-input-completion-response.json').open('w') as out,(a/'review-input-completion-stderr.log').open('w') as err:code=subprocess.run(cmd,cwd=snap,env=env,stdout=out,stderr=err).returncode
(a/'review-input-completion-exit.json').write_text(json.dumps({'session':m['session'],'exit_code':code,'duration_seconds':round(time.monotonic()-t,2)},indent=2));print('input completion exit',code,flush=True)
