<?php

declare(strict_types=1);

use AzGuard\Commands\AbilitiesCommand;
use AzGuard\Commands\CacheResetCommand;
use AzGuard\Commands\CatalogListCommand;
use AzGuard\Commands\CatalogValidateCommand;
use AzGuard\Commands\DoctorCommand;
use AzGuard\Commands\ExplainCommand;
use AzGuard\Commands\GrantCommand;
use AzGuard\Commands\GrantsListCommand;
use AzGuard\Commands\InstallCommand;
use AzGuard\Commands\ListPermissionsCommand;
use AzGuard\Commands\ListScopedRolesCommand;
use AzGuard\Commands\MakeGuardAbilitiesCommand;
use AzGuard\Commands\MakeGuardPanelCommand;
use AzGuard\Commands\MakeGuardPermissionCommand;
use AzGuard\Commands\MakeGuardPolicyCommand;
use AzGuard\Commands\MakeGuardRoleCommand;
use AzGuard\Commands\PruneGrantsCommand;
use AzGuard\Commands\RevokeGrantCommand;
use AzGuard\Commands\RoleAssignmentCommand;
use AzGuard\Commands\RolePermissionsCommand;
use AzGuard\Commands\SuperAdminCommand;
use AzGuard\Commands\SyncRolesCommand;
use AzGuard\Context\Commands\ContextGrantCommand;
use AzGuard\Context\Commands\ContextRevokeCommand;
use AzGuard\Filament\Commands\GenerateFilamentPermissionsCommand;
use Illuminate\Console\Command;

/**
 * F44: the CLI reference doc is generated by hand from the registered
 * command list, so nothing enforces it stays in sync. This test is that
 * enforcement — it is the source of truth's mirror: every command actually
 * registered in a service provider MUST appear in the EN reference table
 * (with its exact signature name), and every command name mentioned in the
 * reference table MUST correspond to a real registered command.
 *
 * @return array<class-string<Command>>
 */
function allRegisteredGuardCommandClasses(): array
{
    return [
        // packages/core/src/AzGuardServiceProvider.php
        InstallCommand::class,
        DoctorCommand::class,
        CatalogListCommand::class,
        CatalogValidateCommand::class,
        RolePermissionsCommand::class,
        RoleAssignmentCommand::class,
        MakeGuardPanelCommand::class,
        MakeGuardPermissionCommand::class,
        MakeGuardPolicyCommand::class,
        MakeGuardAbilitiesCommand::class,
        MakeGuardRoleCommand::class,
        ListPermissionsCommand::class,
        ListScopedRolesCommand::class,
        GrantsListCommand::class,
        SyncRolesCommand::class,
        CacheResetCommand::class,
        GrantCommand::class,
        RevokeGrantCommand::class,
        PruneGrantsCommand::class,
        SuperAdminCommand::class,
        ExplainCommand::class,
        AbilitiesCommand::class,
        // packages/context/src/AzGuardContextServiceProvider.php
        ContextGrantCommand::class,
        ContextRevokeCommand::class,
        // packages/filament/src/AzGuardFilamentServiceProvider.php
        GenerateFilamentPermissionsCommand::class,
    ];
}

function cliReferenceDocPath(): string
{
    return __DIR__.'/../../docs/basic-usage/artisan-commands.md';
}

it('lists every registered command class in this drift test\'s own fixture', function (): void {
    // Guards the guard: fixture files themselves stay in lockstep with the
    // provider registrations enumerated in CommandPrefixRegistrationTest —
    // this is a sanity check that the counts line up (22 core + 2 context
    // + 1 filament = 25), so a newly-added command can't silently skip both
    // this test and the reference doc.
    expect(allRegisteredGuardCommandClasses())->toHaveCount(25);
});

it('covers every registered command signature in the CLI reference doc', function (): void {
    $doc = file_get_contents(cliReferenceDocPath());

    expect($doc)->not->toBeFalse();

    foreach (allRegisteredGuardCommandClasses() as $class) {
        $signature = (new $class)->getName();

        $isDocumented = str_contains($doc, "`{$signature}`");

        expect($isDocumented)->toBeTrue(
            "Registered command [{$signature}] ({$class}) is missing from the CLI reference doc — update docs/basic-usage/artisan-commands.md.",
        );
    }
});

it('does not reference a command in the doc that no longer exists', function (): void {
    $doc = file_get_contents(cliReferenceDocPath());

    expect($doc)->not->toBeFalse();

    $registeredNames = array_map(
        static fn (string $class): string => (new $class)->getName(),
        allRegisteredGuardCommandClasses(),
    );

    preg_match_all('/`(guard:[a-z:-]+|make:guard-[a-z-]+)`/', (string) $doc, $matches);

    $mentionedNames = array_unique($matches[1]);

    foreach ($mentionedNames as $mentioned) {
        $isRegistered = in_array($mentioned, $registeredNames, strict: true);

        expect($isRegistered)->toBeTrue(
            "CLI reference doc mentions [{$mentioned}] which is not a registered command — the doc has drifted.",
        );
    }
});

it('keeps every documented command under the guard: or make:guard- prefix taxonomy', function (): void {
    foreach (allRegisteredGuardCommandClasses() as $class) {
        $signature = (string) (new $class)->getName();

        $isRuntime = str_starts_with($signature, 'guard:');
        $isGenerator = str_starts_with($signature, 'make:guard-');

        expect($isRuntime || $isGenerator)->toBeTrue("Unexpected command prefix on {$class}: {$signature}");
    }
});
